PRODUCT = "Smartphone"
TAX_CHAPTER = 16
TAX_CHAPTER_DESCRIPTION = "Maschinen, Apparate, mechanische Geräte und elektrotechnische Waren, Teile davon; Tonaufnahme- oder Tonwiedergabegeräte, Fernseh-Bild- und -Tonaufzeichnungsgeräte oder Fernseh-Bild- und -Tonwiedergabegeräte, Teile und Zubehör für diese Geräte"
INFRASTAT_NUMBER = 85171300
INFRASTAT_DESCRIPTION = "Smartphones"
ORIGIN = "Tschechien"
DESTINATION = ""
WEIGHT = 600
PRICE = 0
